name: senbace
channels:
  - defaults
dependencies:
  - keras=2.10.0
  - keras-preprocessing
  - matplotlib
  - numpy
  - pandas
  - python
  - tensorflow
  - pip:
      - nvidia-cublas-cu11
      - nvidia-cuda-nvrtc-cu11
      - nvidia-cuda-runtime-cu11
      - nvidia-cudnn-cu11
      - pillow
      - streamlit
      - streamlit-camera-input-live
      - streamlit-card
      - streamlit-embedcode
      - streamlit-extras
      - streamlit-faker
      - streamlit-keyup
      - streamlit-toggle-switch
      - streamlit-vertical-slider
      - torch
      - torchvision
