name: senbace
channels:
  - defaults
dependencies:
  - keras=2.10.0
  - keras-preprocessing=1.1.2
  - matplotlib=3.5.3
  - numpy=1.23.4
  - pandas=1.5.1
  - python=3.9.15
  - tensorflow=2.10.0
  - pip:
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - pillow==9.3.0
      - streamlit==1.15.2
      - streamlit-camera-input-live==0.2.0
      - streamlit-card==0.0.4
      - streamlit-embedcode==0.1.2
      - streamlit-extras==0.2.4
      - streamlit-faker==0.0.2
      - streamlit-keyup==0.2.0
      - streamlit-toggle-switch==1.0.2
      - streamlit-vertical-slider==1.0.2
      - torch==1.13.0
      - torchvision==0.14.0
